apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-reservation-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-reservation-backend
  template:
    metadata:
      labels:
        app: clinic-reservation-backend
    spec:
      containers:
      - name: clinic-reservation-backend
        image: back-end  # Replace with the actual image name
        ports:
        - containerPort: 8084
        env:
        - name: PORT
          value: "8084"
        - name: MONGODB_URI
          value: "mongodb://clinic-reservation-mongodb:27017/usersdb"
        - name: ANGULAR_URI
          value: "http://clinic-reservation-frontend"  # Replace with your front-end service name
        - name: ANGULAR_PORT
          value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-reservation-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-reservation-frontend
  template:
    metadata:
      labels:
        app: clinic-reservation-frontend
    spec:
      containers:
      - name: clinic-reservation-frontend
        image: front-end  # Replace with the actual image name
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_API_URI
          value: "http://clinic-reservation-backend:8084"
        - name: ANGULAR_PORT
          value: "5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-reservation-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-reservation-mongodb
  template:
    metadata:
      labels:
        app: clinic-reservation-mongodb
    spec:
      containers:
      - name: clinic-reservation-mongodb
        image: data-base  # Replace with the actual image name
        ports:
        - containerPort: 27017
