version: "3"
services:
  mongodb:
    build:
      context: ./data-base
    container_name: mongodb
    ports:
      - "${MONGODB_PORT:-27017}:27017"

  back-end:
    build:
      context: ./back-end # Replace with the actual path to your backend code
      args:
        - PORT=${BACKEND_API_PORT:-8084}
        - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:${MONGODB_PORT:-27017}/usersdb}
        - ANGULAR_URI=${ANGULAR_URI:-https://clinicfrontt-khaleddkassab-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/}
        - ANGULAR_PORT=
    container_name: back-end
    restart: always
    ports:
      - ${BACKEND_API_PORT:-8084}:${BACKEND_API_PORT:-8084}
    depends_on:
      - mongodb
      - front-end
    environment:
      - BACKEND_API_PORT=${BACKEND_API_PORT:-8084}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:${MONGODB_PORT:-27017}/usersdb}
      - ANGULAR_URI=${ANGULAR_URI:-https://clinicfrontt-khaleddkassab-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/}
      - ANGULAR_PORT

  front-end:
    build:
      context: ./front-end # Replace with the actual path to your frontend code
    container_name: front-end
    ports:
      - ${ANGULAR_PORT:-5000}:80
    env_file:
      - front-end/.env
