# Use the official MongoDB image as the base image
FROM mongo

# Set the working directory inside the container
WORKDIR /data/db

# Expose the default MongoDB port
EXPOSE 27017

# Start the MongoDB server when the container starts
CMD ["mongod"]
